export const vcFieldMocks = {
	incomeCertificate: [
		{ id: 'studentuniqueid', label: 'Student Unique ID', type: 'string' },
		{ id: 'schoolid', label: 'School ID', type: 'string' },
		{ id: 'schoolname', label: 'School Name', type: 'string' },
		{ id: 'firstname', label: 'First Name', type: 'string' },
		{ id: 'fathername', label: 'Father Name', type: 'string' },
		{ id: 'mothername', label: 'Mother Name', type: 'string' },
		{ id: 'husbandname', label: 'Husband Name', type: 'string' },
		{ id: 'wifename', label: 'Wife Name', type: 'string' },
		{ id: 'addressline1', label: 'Address Line 1', type: 'string' },
		{ id: 'district', label: 'District', type: 'string' },
		{ id: 'pin', label: 'PIN', type: 'number' },
		{ id: 'state', label: 'State', type: 'string' },
		{ id: 'country', label: 'Country', type: 'string' },
		{ id: 'castename', label: 'Caste Name', type: 'string' },
		{ id: 'castecategory', label: 'Caste Category', type: 'string' },
		{ id: 'annualincome', label: 'Annual Income', type: 'number' },
		{
			id: 'agricultureincome',
			label: 'Agriculture Income',
			type: 'number',
		},
		{ id: 'salaryincome', label: 'Salary Income', type: 'number' },
		{ id: 'businessincome', label: 'Business Income', type: 'number' },
		{ id: 'otherincome', label: 'Other Income', type: 'number' },
		{ id: 'issuedby', label: 'Issued By', type: 'string' },
		{ id: 'issuerauthority', label: 'Issuer Authority', type: 'string' },
		{ id: 'issueddate', label: 'Issued Date', type: 'string' },
		{ id: 'validupto', label: 'Valid Upto', type: 'string' },
		{ id: 'originalvc', label: 'Original VC', type: 'object' },
		{ id: 'issueraddress', label: 'Issuer Address', type: 'string' },
		{ id: 'vtc', label: 'VTC', type: 'string' },
	],

	marksheet: [
		{ id: 'studentuniqueid', label: 'Student Unique ID', type: 'string' },
		{ id: 'firstname', label: 'First Name', type: 'string' },
		{ id: 'middlename', label: 'Middle Name', type: 'string' },
		{ id: 'lastname', label: 'Last Name', type: 'string' },
		{ id: 'schoolid', label: 'School ID', type: 'string' },
		{ id: 'schoolname', label: 'School Name', type: 'string' },
		{ id: 'currentclass', label: 'Current Class', type: 'number' },
		{ id: 'previousclass', label: 'Previous Class', type: 'number' },
		{ id: 'examdate', label: 'Exam Date', type: 'string' },
		{ id: 'cgpa', label: 'CGPA', type: 'number' },
		{ id: 'cgpamax', label: 'CGPA Max', type: 'number' },
		{ id: 'grade', label: 'Grade', type: 'string' },
		{ id: 'marksmax', label: 'Max Marks', type: 'number' },
		{ id: 'markstotal', label: 'Total Marks', type: 'number' },
		{ id: 'percentage', label: 'Percentage', type: 'number' },
		{ id: 'result', label: 'Result', type: 'string' },
		{ id: 'academicyear', label: 'Academic Year', type: 'string' },
		{ id: 'issuedby', label: 'Issued By', type: 'string' },
		{ id: 'issuerauthority', label: 'Issuer Authority', type: 'string' },
		{ id: 'issueddate', label: 'Issued Date', type: 'string' },
		{ id: 'validupto', label: 'Valid Upto', type: 'string' },
		{ id: 'originalvc', label: 'Original VC', type: 'object' },
		{ id: 'originalvc1', label: 'Original VC 1', type: 'object' },
		{
			id: 'issuingauthorityaddress',
			label: 'Issuing Authority Address',
			type: 'string',
		},
		{
			id: 'issuingauthoritydistrict',
			label: 'Issuing Authority District',
			type: 'string',
		},
		{ id: 'issuingauthoritypin', label: 'PIN Code', type: 'number' },
		{ id: 'issuingauthoritystate', label: 'State', type: 'string' },
		{ id: 'issuingauthoritycountry', label: 'Country', type: 'string' },
	],

	otrCertificate: [
		{ id: 'otr_number', label: 'OTR Number', type: 'number' },
		{ id: 'firstname', label: 'First Name', type: 'string' },
		{ id: 'middlename', label: 'Middle Name', type: 'string' },
		{ id: 'lastname', label: 'Last Name', type: 'string' },
		{ id: 'date_of_birth', label: 'Date of Birth', type: 'string' },
		{ id: 'gender', label: 'Gender', type: 'string' },
		{ id: 'father_name', label: 'Father Name', type: 'string' },
		{ id: 'mother_name', label: 'Mother Name', type: 'string' },
		{ id: 'aadhaar', label: 'Aadhaar Number', type: 'number' },
		{ id: 'issuedby', label: 'Issued By', type: 'string' },
		{ id: 'issuerauthority', label: 'Issuer Authority', type: 'string' },
		{ id: 'issued_date', label: 'Issued Date', type: 'string' },
		{ id: 'validupto', label: 'Valid Upto', type: 'string' },
		{ id: 'original_vc', label: 'Original VC', type: 'object' },
	],

	disabilityCertificate: [
		{ id: 'name', label: 'Name', type: 'string' },
		{ id: 'gender', label: 'Gender', type: 'string' },
		{ id: 'aadhaar_number', label: 'Aadhaar Number', type: 'number' },
		{ id: 'unique_disability_id_(udid)', label: 'UDID', type: 'string' },
		{ id: 'disability_type', label: 'Disability Type', type: 'string' },
		{ id: 'birthyear', label: 'Birth Year', type: 'number' },
		{
			id: 'percentage_of_disability',
			label: 'Disability %',
			type: 'number',
		},
		{
			id: 'validitycertificate',
			label: 'Validity Certificate',
			type: 'string',
		},
		{ id: 'issuedby', label: 'Issued By', type: 'string' },
		{ id: 'issuerauthority', label: 'Issuer Authority', type: 'string' },
		{ id: 'issueddate', label: 'Issued Date', type: 'string' },
		{ id: 'recordvalidupto', label: 'Record Valid Upto', type: 'string' },
		{ id: 'originalvc', label: 'Original VC', type: 'object' },
		{ id: 'originalvc1', label: 'Original VC 1', type: 'object' },
		{ id: 'studentuniqueid', label: 'Student Unique ID', type: 'string' },
		{
			id: 'issuingauthorityaddress',
			label: 'Issuer Address',
			type: 'string',
		},
		{
			id: 'issuingauthoritydistrict',
			label: 'Issuer District',
			type: 'string',
		},
		{ id: 'issuingauthoritypin', label: 'Issuer PIN', type: 'string' },
		{ id: 'issuingauthoritystate', label: 'Issuer State', type: 'string' },
		{
			id: 'issuingauthoritycountry',
			label: 'Issuer Country',
			type: 'string',
		},
		{
			id: 'certificate_validaity_date',
			label: 'Certificate Validity Date',
			type: 'string',
		},
		{
			id: 'issuingauthoritysignature',
			label: 'Authority Signature',
			type: 'object',
		},
		{
			id: 'disabiltycategorysymbol',
			label: 'Disability Symbol',
			type: 'object',
		},
		{ id: 'stateid', label: 'State ID', type: 'string' },
		{ id: 'photograph', label: 'Photograph', type: 'object' },
		{ id: 'issuedlanguage', label: 'Issued Language', type: 'string' },
	],

	feeReceipt: [
		{ id: 'school_id', label: 'School ID', type: 'string' },
		{ id: 'student_unique_id', label: 'Student Unique ID', type: 'string' },
		{ id: 'first_name', label: 'First Name', type: 'string' },
		{ id: 'middle_name', label: 'Middle Name', type: 'string' },
		{ id: 'last_name', label: 'Last Name', type: 'string' },
		{ id: 'academic_year', label: 'Academic Year', type: 'string' },
		{ id: 'class', label: 'Class', type: 'number' },
		{ id: 'school_name', label: 'School Name', type: 'string' },
		{ id: 'locality', label: 'Locality', type: 'string' },
		{ id: 'district', label: 'District', type: 'string' },
		{ id: 'state', label: 'State', type: 'string' },
		{ id: 'pin', label: 'PIN Code', type: 'number' },
		{ id: 'country', label: 'Country', type: 'string' },
		{
			id: 'tuition_and_admin_fee_paid',
			label: 'Tuition/Admin Fee',
			type: 'number',
		},
		{ id: 'misc_fee_paid', label: 'Misc Fee Paid', type: 'number' },
		{ id: 'issued_by', label: 'Issued By', type: 'string' },
		{ id: 'issuer_authority', label: 'Issuer Authority', type: 'string' },
		{ id: 'issuance_date', label: 'Issuance Date', type: 'string' },
		{
			id: 'credential_validity_date',
			label: 'Credential Validity Date',
			type: 'string',
		},
		{ id: 'originalvc', label: 'Original VC', type: 'object' },
		{ id: 'originalvc1', label: 'Original VC 1', type: 'object' },
		{ id: 'address_line1', label: 'Address Line 1', type: 'string' },
		{ id: 'student_status', label: 'Student Status', type: 'string' },
		{ id: 'address_line_2', label: 'Address Line 2', type: 'string' },
		{ id: 'landmark', label: 'Landmark', type: 'string' },
		{
			id: 'address_of_card_issuing_authority',
			label: 'Authority Address',
			type: 'string',
		},
		{
			id: 'issuing_authority_district',
			label: 'Authority District',
			type: 'string',
		},
		{
			id: 'issuing_authority_pin_code',
			label: 'Authority PIN',
			type: 'number',
		},
		{
			id: 'issuing_authority_state',
			label: 'Authority State',
			type: 'string',
		},
		{
			id: 'issuing_authority_country',
			label: 'Authority Country',
			type: 'string',
		},
		{
			id: 'school_registration_number',
			label: 'School Reg. Number',
			type: 'string',
		},
	],

	enrollmentCertificate: [
		{ id: 'schoolid', label: 'School ID', type: 'string' },
		{ id: 'studentuniqueid', label: 'Student Unique ID', type: 'string' },
		{ id: 'schoolname', label: 'School Name', type: 'string' },
		{ id: 'firstname', label: 'First Name', type: 'string' },
		{ id: 'middlename', label: 'Middle Name', type: 'string' },
		{ id: 'lastname', label: 'Last Name', type: 'string' },
		{ id: 'academicyear', label: 'Academic Year', type: 'string' },
		{ id: 'class', label: 'Class', type: 'string' },
		{ id: 'locality', label: 'Locality', type: 'string' },
		{ id: 'district', label: 'District', type: 'string' },
		{ id: 'pin', label: 'PIN Code', type: 'number' },
		{ id: 'state', label: 'State', type: 'string' },
		{ id: 'country', label: 'Country', type: 'string' },
		{ id: 'studentstatus', label: 'Student Status', type: 'string' },
		{ id: 'issuedby', label: 'Issued By', type: 'string' },
		{ id: 'issuerauthority', label: 'Issuer Authority', type: 'string' },
		{ id: 'issueddate', label: 'Issued Date', type: 'string' },
		{ id: 'validupto', label: 'Valid Upto', type: 'string' },
		{ id: 'originalvc', label: 'Original VC', type: 'object' },
		{
			id: 'issuingauthorityaddress',
			label: 'Issuer Address',
			type: 'string',
		},
		{
			id: 'issuingauthoritydistrict',
			label: 'Issuer District',
			type: 'string',
		},
		{ id: 'issuingauthoritypin', label: 'Issuer PIN', type: 'string' },
		{ id: 'issuingauthoritystate', label: 'Issuer State', type: 'string' },
		{
			id: 'issuingauthoritycountry',
			label: 'Issuer Country',
			type: 'string',
		},
		{ id: 'authorityname', label: 'Authority Name', type: 'string' },
		{ id: 'designationprincipal', label: 'Designation', type: 'string' },
	],
};
